'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Tips
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DWSIM.Tips", GetType(Tips).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para calcular o fluxograma rapidamente, clique em qualquer área livre e pressione F5..
        '''</summary>
        Friend Shared ReadOnly Property FLSH001() As String
            Get
                Return ResourceManager.GetString("FLSH001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilize a ferramenta de conexão rápida disponível na barra de ferramentas  para conectar rapidamente um objeto a outro enquanto pressiona a tecla CTRL..
        '''</summary>
        Friend Shared ReadOnly Property FLSH002() As String
            Get
                Return ResourceManager.GetString("FLSH002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressione SHIFT durante a inicialização do DWSIM para fazer com que as configurações voltem aos seus valores-padrão..
        '''</summary>
        Friend Shared ReadOnly Property FLSH003() As String
            Get
                Return ResourceManager.GetString("FLSH003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Você pode editar a composição de uma corrente de matéria através de um duplo clique com o botão esquerdo do mouse em seu objeto no fluxograma..
        '''</summary>
        Friend Shared ReadOnly Property MSTR001() As String
            Get
                Return ResourceManager.GetString("MSTR001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O menu de contexto da corrente no fluxograma oferece algumas ferramentas úteis para o gerenciamento dos dados de uma corrente, tais como a cópia dos dados de outra corrente, restauração dos dados originais, exportação dos dados para a área de transferência, etc..
        '''</summary>
        Friend Shared ReadOnly Property MSTR002() As String
            Get
                Return ResourceManager.GetString("MSTR002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para evitar que a caixa de edição de composição da corrente de matéria apareça ao inserir uma no fluxograma, pressione SHIFTenquanto executa esta ação..
        '''</summary>
        Friend Shared ReadOnly Property MSTR003() As String
            Get
                Return ResourceManager.GetString("MSTR003", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
